### ISSUE TITLE
Incorrect description of IP Whitelist

### ISSUE THREAD

**Issue by yyamano** [mulesoft/docs-anypoint-security#17]
https://github.com/mulesoft/docs-anypoint-security/blob/latest/modules/ROOT/pages/index-policies.adoc  says:

```
IP Whitelist
These policies check HTTP protocol message size and headers.
Learn more about the IP Whitelist.
```

I don't think IP Whitelist checks message size and headers.

**Comment by valkyrie69** [comment]
Thank you for this. You are correct.
