### ISSUE TITLE
W-13631494 "Certificate Checking Strength" is not documented properly

### ISSUE THREAD

**Issue by lol768** [mulesoft/docs-anypoint-security#68]
https://github.com/mulesoft/docs-anypoint-security/blob/latest/modules/ROOT/pages/enable-client-authentication.adoc

>  Allows the application to control whether strict or lax certificate checking is performed during chain-of-trust processing.

What does strict mean? What does lax mean? What do these options actually _do_?

**Comment by valkyrie69** [comment]
Hi @lol768 I know that this is a very tardy response, and I apologize for that. Thank you for your feedback. I will look into this and let you know about any updates to the documentation.

**Comment by valkyrie69** [comment]
Merged documentation after technical review. 
https://github.com/mulesoft/docs-anypoint-security/pull/100
